accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('edit/', views.edit, name="edit"),
    path('password/', views.chg_pwd, name="chg_pwd"),
    path('delete/', views.delete, name="delete"),
    path('follow/<int:u_id>/', views.follow, name="follow"),
    path('profile/<str:name>/', views.profile, name="profile"),
]

boards/urls.py
from django.urls import path
from . import views

app_name='boards'

urlpatterns =[
    path('', views.index, name="index"),
    path('new/', views.new, name="new"),
    path('<int:b_id>/', views.detail, name="detail"),
    path('edit/<int:b_id>/', views.edit, name="edit"),
    path('delete/<int:b_id>/', views.delete, name="delete"),
    path('new_comment/<int:b_id>/', views.new_comment, name="new_comment"),
    path('del_comment/<int:c_id>/', views.del_comment, name="del_comment"),
    path('like/<int:b_id>/', views.like, name="like"),
    path('search/', views.search, name="search"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('boards/', include('boards.urls')),
    path('admin/', admin.site.urls),
]

boards/models.py
from django.db import models
from django.conf import settings

class Board(models.Model):
    title = models.CharField(max_length=30)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # 좋아요 로직 구현을 위해 추가
    # related_name을 설정하지 않으면 user에서 board_set으로 접근
    # 근데 위에 ForeignKey로 연결된 user도 board_set으로 접근하게됨.
    # 이름이 겹치게됨. 장고는 혼란에 빠지게됨.
    # 그래서 related_name을 설정해주어 장고가 구분할수 있게됨.
    # 최종적으로 FK로 접근을 할땐 board_set / MtM으로 접근할땐 like_boards
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="like_boards", blank=True)

    def __str__(self):
        return self.title
    
class Comment(models.Model):
    comment = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    board = models.ForeignKey(Board, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

boards/forms.py
from django import forms
from .models import Board, Comment

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['comment'].widget.attrs.update(
    #         {
    #             'class':'form-control-sm', 
    #             'id':'abcdef'
    #         }
    #         )

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import BoardForm, CommentForm
from .models import Board, Comment
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.contrib.auth import get_user_model
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponseBadRequest

def index(request):
    boards = Board.objects.all()

    # Paginator(전체리스트 , 페이지당 보여지는 갯수)
    paging = Paginator(boards, 5)

    page = request.GET.get('page')
    page_list = paging.get_page(page)

    context = {
        'boards':page_list
    }
    return render(request, 'boards/index.html', context)

@login_required
def new(request):
    if request.method == "POST":
        form = BoardForm(request.POST)
        
        if form.is_valid():
            # DB에 바로 적용하지 않고 form이 참고하는 모델로 인스턴스를 만들어줌.
            board = form.save(commit=False)
            # 게시글의 유저 정보를 저장
            board.user = request.user
            # 게시글을 DB에 저장
            board.save()

            return redirect('boards:index')

    else:
        form = BoardForm()

    context = {
        'form':form
    }
    return render(request, 'boards/new.html', context)

def detail(request, b_id):
    board = get_object_or_404(Board, id=b_id)
    # 댓글 달기 폼 생성
    comment_form = CommentForm()
    # 게시글이 가진 모든 댓글을 가져옴
    comments = board.comment_set.all()
    person = get_object_or_404(get_user_model(), id=board.user.id)
    context = {
        'board':board,
        'comment_form': comment_form,
        'comments': comments,
        'person': person,
    }
    return render(request, 'boards/detail.html', context)

@login_required
def edit(request, b_id):
    # Board 모델 안에 해당 값이 있으면 가져오고 없으면 404 에러 발생
    board = get_object_or_404(Board, id=b_id)

    # 현재 로그인 유저와 게시글 작성 유저 비교
    if request.user != board.user:
        return redirect('boards:index')

    if request.method == "POST":
        # instance에 위에서 찾은 board 값을 지정.
        # 그렇게 하면 db에 저장된 내용이 Form에 적용됨.
        # 첫번째 인자로 request.POST가 있으면
        # POST 로 받은 데이터 내용이 폼에 씌여짐.
        # board의 내용으로 적용된 Form에 새롭게 POST로 받은 데이터까 씌여짐.
        # 즉 수정되게됨.
        form = BoardForm(request.POST, instance=board)
        if form.is_valid():
            board = form.save()
            return redirect('boards:detail', board.id)
    else:
        # 폼을 이미 저장된 내용으로 채우기 위해 instance=board 사용
        form = BoardForm(instance=board)

    context = {
        'form': form
    }
    return render(request, 'boards/edit.html', context)

@login_required
def delete(request, b_id):
    board = get_object_or_404(Board, id=b_id)

    if request.user != board.user:
        return redirect('boards:index')
        
    if request.method == "POST":
        board.delete()
        return redirect('boards:index')

    return redirect('boards:detail', board.id)

@login_required
@require_POST
def new_comment(request, b_id):
    form = CommentForm(request.POST)

    if form.is_valid():
        # 댓글 모델은 게시글과 유저 정보가 필요해서 바로저장을 시키지 않음.
        comment = form.save(commit=False)
        comment.board_id = b_id # 게시글 정보 저장
        comment.user = request.user # 유저 정보 저장
        comment.save() # 최종 db에 저장
        return redirect('boards:detail', b_id)
    else: # 유효성 검사에 실패했을때.
        board = Board.objects.get(id=b_id)
        comments = board.comment_set.all()

        context = {
            'board':board,
            'comment_form':form,
            'comments':comments
        }
        return render(request, 'boards/detail.html', context)

@login_required
@require_POST
def del_comment(request, c_id):
    comment = get_object_or_404(Comment, id=c_id)
    # 게시글의 정보가 필요해서 삭제되기 전에 저장.
    board_id = comment.board_id
    if request.user == comment.user:
        comment.delete()

    return redirect('boards:detail', board_id)

@login_required
def like(request, b_id):
    board = get_object_or_404(Board, pk=b_id)

    if request.is_ajax():
        # 좋아요를 저장해두는 곳에 유저가 있는지 확인
        # if board.like_users.filter(id=request.user.id).exists()
        if request.user in board.like_users.all():
            # 있으면 목록에서 제거
            board.like_users.remove(request.user)
            liked = False
        else:
            # 없으면 목록에 등록
            board.like_users.add(request.user)
            liked = True
        count = len(board.like_users.all())
        context = {
            'liked': liked,
            'count': count
        }
        return JsonResponse(context)
    else:
        return HttpResponseBadRequest
    # return redirect('boards:index')

def search(request):
    text = request.GET.get('search')

    results = Board.objects.filter(title__contains=text)

    context={
        'results': results
    }
    return render(request, 'boards/search.html', context)

boards/templates/boards/_board.html
<div class="card-body">
    <!-- <a href="{#% url 'boards:like' board.id %}" class="card-link"> -->
        <p class="card-text">
            <!-- 현재 유저가 좋아요 리스트에 있는지 확인 -->
            {% if user in board.like_users.all %}
                <i class="like-button fas fa-heart fa-lg" style="color:crimson" data-id="{{ board.id }}"></i>
            {% else %}
                <i class="like-button far fa-heart fa-lg" style="color:black" data-id="{{ board.id }}"></i>
            {% endif %}
        <!-- </a> -->
            <span id="like-count-{{ board.id }}">{{ board.like_users.all|length }} 명이 좋아합니다</span>
            <!-- {#{ board.like_users.all|length }} 명이 좋아합니다. -->
        </p>
</div>

boards/templates/boards/_follow.html
<div>
    <p>작성자 정보</p>
    <h2>{{ board.user }}</h2>
    <hr>
    {% if user != board.user %}
        {% if user in person.followers.all %}
        <a href="{% url 'accounts:follow' person.id %}">언팔로우</a>
        {% else %}
        <a href="{% url 'accounts:follow' person.id %}">팔로우</a>
        {% endif %}
    {% endif %}
    <div>
        팔로잉: {{ person.followings.all|length }}
        팔로워: {{ person.followers.all|length }}
    </div>
</div>

boards/templates/boards/_page.html
<nav>
    <ul class="pagination">
        {% if boards.has_previous %}
        <li class="page-item">
            <a href="{% url 'boards:index' %}?page={{ boards.previous_page_number }}" class="page-link">Prev</a>
        </li>
        {% endif %}

        {% for page_num in boards.paginator.page_range %}
        <li class="page-item {% if page_num == boards.number %} active {% endif %}">
            <a href="{% url 'boards:index' %}?page={{ page_num}}" class="page-link">{{ page_num }}</a>
        </li>
        {% endfor %}

        {% if boards.has_next %}
        <li class="page-item">
            <a href="{% url 'boards:index' %}?page={{ boards.next_page_number }}" class="page-link">Next</a>
        </li>
        {% endif %}
    </ul>
</nav>

boards/templates/boards/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block body %}
<table>
    <tr>
        <td>타이틀</td>
        <td>{{ board.title }}</td>
    </tr>
    <tr>
        <td>내용</td>
        <td>{{ board.content }}</td>
    </tr>
</table>
<!-- 댓글 보여주기 -->
<hr>
{% include "boards/_follow.html" %}
<hr>
<h3>댓글</h3>
{% for comment in comments %}
    <p><b>{{ comment.comment }}</b> - {{ comment.user }} </p>
    {% if user == comment.user %}
    <form action='{% url "boards:del_comment" comment.id %}' method='POST'>
        {% csrf_token %}
        <a href="#" onclick="this.parentNode.submit()">댓글 삭제</a>
    </form>
    {% endif %}

{% empty %}
    <h4>작성된 댓글이 없어요.</h4>
{% endfor %}
<hr>

<form action='{% url "boards:new_comment" board.id %}' method='POST'>
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    {% buttons submit="댓글등록" %}
    {% endbuttons %}
</form>





{% if user == board.user %}
<a href="{% url 'boards:edit' board.id %}">수정하기</a>

<form action="{% url 'boards:delete' board.id %}" method="post">
    {% csrf_token %}
    <a href="#" onclick="this.parentNode.submit()">삭제하기</a>
</form>
{% endif %}

{% endblock %}

boards/templates/boards/edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
 <form action="" method="POST">
 {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="수정하기">
 </form>
{% endblock %}

boards/templates/boards/index.html
{% extends 'base.html' %}
{% block body %}
<h1>Index Page</h1>
<ul>
    {% for board in boards %}
        <li><a href="{% url 'boards:detail' board.id %}">{{ board.title }}</a> - 
            <a href="{% url 'accounts:profile' board.user %}">{{ board.user }}</a></li>
        <!-- 분할된 템플릿은 _(언더바)로 이름이 시작하는게 관례 -->
        <!-- 분할된 템플릿 파일 불러오기 -->
        {% include 'boards/_board.html' %}
    {% endfor %}
</ul>
{% include 'boards/_page.html' %}

{% if user.is_authenticated %}
    <a href="{% url 'boards:new' %}">New</a><br>
{% else %}
    <h3>로그인 해야 글을 작성 할수 있습니다.</h3>
{% endif %}


<script>
    const likeButtons = document.querySelectorAll('.like-button')

    likeButtons.forEach(button => {
        button.addEventListener('click', function(event){
            // console.log(event)
            // 1. data-id에는 board.id 가 들어 있으며 동적 라우팅에 사용.
            const boardId = event.target.dataset.id
            axios.defaults.xsrfCookieName = 'csrftoken'
            axios.defaults.xsrfHeaderName = 'X-CSRFToken'
            axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest'
            // 2. 해당 게시글의 좋아요 요청을 보낸다.
            {% if user.is_authenticated %}
            axios.post(`/boards/like/${boardId}/`)
            .then(response => {
            // 3. 응답을 확인한다.
                console.log(response.data)
                if (response.data.liked){
                    event.target.style.color = 'crimson'
                    event.target.classList.replace('far', 'fas')
                }else {
                    event.target.style.color = 'black'
                    event.target.classList.replace('fas', 'far')
                }
                // 알맞은 id 값을 가진 span 태그를 선택해서,
                // 사용자가 좋아요 누를 때마다 response.data.count 값으로 갱신시킴
                document.querySelector(`#like-count-${boardId}`).innerText = `${response.data.count} 명이 좋아합니다`
            })
            .catch(error => console.log(error))
            {% else %}
                alert('로그인이 필요합니다.')
            {% endif %}
        })
    })

</script>
{% endblock %}

boards/templates/boards/new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block body %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="새글쓰기">
</form>
{% endblock %}

boards/templates/boards/search.html
{% extends 'base.html' %}
{% block body %}
<h1>검색 결과</h1>
<ul>
    {% for res in results %}
    <li><a href="{% url 'boards:detail' res.id %}">{{ res.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}